### ISSUE TITLE
Inputting images into 3 states of RNN

### ISSUE THREAD

**Issue by RaviTej310** [Element-Research/rnn#276]
How can I build an RNN model with three unrolled states(t-3,t-2 and t-1) which accepts three images of dimensions 200x200 and predicts a fourth image? What would I need to change in this [RNN example](https://github.com/Element-Research/rnn/blob/master/examples/simple-recurrent-network.lua)?

**Comment by viorik** [comment]
@RaviTej310 in case you want to use a convolutional LSTM, you could have a look [here](https://github.com/viorik/ConvLSTM/blob/master/main-demo-ConvLSTM.lua) for an example of predicting the next frame in a sequence.

**Comment by RaviTej310** [comment]
I would not like to use that link as it uses cunn and cutorch for which I need to install CUDA and everything. This is unfortunately not possible for me. Is there any way I can modify the code in the link I have given?

**Comment by viorik** [comment]
@RaviTej310 I am not sure what is needed to make that example work on images. The example in the link I sent can be run on CPU as well, if instead of using the SpatialConvolutionalNoBias from extracunn, you use the normal SpatialConvolution and call noBias to cancel the bias. I can advise you if you want to make that work.

**Comment by RaviTej310** [comment]
Sure. Please advise. Thanks for the help!

**Comment by viorik** [comment]
I've uploaded [here](https://github.com/viorik/ConvLSTM_CPU) a simple demo of the CPU version. Please post there to let me know if you manage to run it or not.
cheers.
