### ISSUE TITLE
Why maskZero work

### ISSUE THREAD

**Issue by OptimusPrimeCao** [Element-Research/rnn#318]
Hi,@nicholas-leonard
![image](https://cloud.githubusercontent.com/assets/11535540/17509493/c605f682-5e4c-11e6-8667-fcb589da2349.png)
In the last sentence, it is said that the hidden state is reset . However I can't find the implementation wrt this part in your code . Could u please point out it ? Thanks !

**Comment by nicholas-leonard** [comment]
@OptimusPrimeCao Basically, because MaskZero is applied to internal recurrentModule of the RNN for each time-step, then when https://github.com/Element-Research/rnn/blob/master/MaskZero.lua#L77 it zeros the outputs for each (step, row) that is zero in the input. So that effectively forgets by creating a discontinuity in between previous and next state. The simple principle is applied for the commensurate gradients with respect to input : https://github.com/Element-Research/rnn/blob/master/MaskZero.lua#L85. 

Caveat: this does not mean that the outputs and gradInputs of the internal modules making up a recurrentModule will all by zeros as well. MaskZero only affects the immediate gradInput and output of the module that it encapsulates.

**Comment by nicholas-leonard** [comment]
@OptimusPrimeCao I update the doc: https://github.com/Element-Research/rnn#maskzero . Thanks for bringing this up!
