### ISSUE TITLE
Prefer if examples dont need dp

### ISSUE THREAD

**Issue by hughperkins** [Element-Research/rnn#60]
I reckon it would be easier to use the examples if they didnt need one to learn dp to understand them fully.

Basically, currently one has to kind of learn both rnn and dp together, to understand the examples.  I reckon it would be faster learning curve if the examples in rnn assumed only knowledge of rnn, and core Torch libraries, such as nn etc.

**Comment by nicholas-leonard** [comment]
@hughperkins Yeah I could use optim instead. But then one one need to learn optim to understand the examples. Personally, I am not a big fan of optim. I find the all inclusive closure arguments difficult to understand. I also don't like it's reliance on the getParameters() method. I prefer layer-wise calls then one giant call applied to all params/gradParams. But of course those are just personal preferences. I built dp because I was used to pylearn2's way of doing things. 

In any case, dp provides a framework for doing experiments, which is something none of the core packages do AFAIK. Every script includes its own implementation of cross-validation. All this variation makes it difficult to separate the wheat from the chaff IMHO. Of course, I built dp so maybe I take it for granted.

Anyway, I agree that we should have optim examples (i.e. non-dp examples). But I think we should still rely on dp to at least provide the data. And yeah, I reckon dp ain't perfect or easy to learn. But its what I know best. Maybe I should try to reproduce some of @karpathy 's code using the rnn package instead of nngraph. That way I could learn optim from his examples, which are pretty good. That could also mean more examples for rnn.

**Comment by hughperkins** [comment]
> Yeah I could use optim instead.

Yes, or maybe a simple SGD for-loop perhaps?  I assume the examples are mostly there for us to base our own work on, than to provide high performance benchmarks?  (Might be an invalid assumption though?)

> But I think we should still rely on dp to at least provide the data.

Yes, seems very reasonable to me.  I was thinking the same thing actually :-)

> Maybe I should try to reproduce some of @karpathy 's code using the rnn package instead of nngraph

Funnily enough, I'm exactly targeting trying to do char-rnn using your rnn library instead of the char-rnn library :-)  I think that it's probably a bit more work to get rnn working, but then it seems plausibly more modular, transparent, easier to maintain, perhaps.

**Comment by nicholas-leonard** [comment]
>> Yeah I could use optim instead.

>Yes, or maybe a simple SGD for-loop perhaps?  I assume the examples are mostly there for us to base our own work on, than to provide high performance benchmarks?  (Might be an invalid assumption though?)

The recurrent language (the one in the dp repository itself) and recurrent attention models are benchmarked against existing papers. But the encoder-decoder is an unbenchmarked example. So we can have both.

>> But I think we should still rely on dp to at least provide the data.

>Yes, seems very reasonable to me.  I was thinking the same thing actually :-)

>> Maybe I should try to reproduce some of karpathy 's code using the rnn package instead of nngraph

>Funnily enough, I'm exactly targeting trying to do char-rnn using your rnn library instead of the char-rnn library :-)  I think that it's probably a bit more work to get rnn working, but then it seems plausibly more modular, transparent, using standardized building bricks, perhaps.

Yeah. The nn package philosophy is to encapsulate transformations within modules as much as possible. rnn does that. The usual nngraph solutions don't (unless its a fixed length sequence for both training and evaluation). 

I would love to see the char-rnn script rewritten with rnn!

**Comment by jfsantos** [comment]
Hi,

sorry to get into the conversation, but I am working on a model which looks like char-rnn using rnn and want to use optim as well, so I think my comment is at least a bit relevant :)

The way char-rnn was initially implemented, the model does not predict a sequence, but a single character each time. Therefore, using nn.SequencerCriterion for the output does not work. One cannot use a `nn.___Criterion` as the behavior is different: models wrapped by rnn.Sequencer require a `gradOutput` table, not a single gradient vector. @nicholas-leonard, any tips on how to train such a model using rnn?

**Comment by nicholas-leonard** [comment]
@jfsantos hi. So I think the char-rnn character-level LM is trained the same way you train a word-level LM. Your model takes as input a sequence of words : w[1], w[2] ... w[T] for which the targets are also 
a sequence of words : w[2], w[3] ... w[T+1] where T is the size of your training sequence (`rho` in our code here). So you would use a Sequencer for that with a SequencerCriterion.

However, when you want to generate sequences, you need to generate one word at a time. So what you do is call `sequencer:remember('both')` so that it will remember past inputs. You can also do `sequencer:evaluate()` to reduce memory consumption during sequence generation. Then you just forward a random word w[1] as a table of just one element : `{w[1]}`.The output will be a table containing one element : the distribution over `logP(w[2]|w[1])` (i.e. output of a logsoftmax).  If you take the max of that distribution, you will get the Maximum A Posteriori (MAP) value for w[2]. Then you can feed `{w[2]}` as input to get `w[3]`, an so forth and so on. 

Based on what I could gather from @karpathy  's [blog post](http://karpathy.github.io/2015/05/21/rnn-effectiveness/), I think this is how he goes to generate sequences.

**Comment by jfsantos** [comment]
Thank you for your answer, @nicholas-leonard!

I think you are right regarding char-rnn. However, the model I am currently implementing sees an entire sequence before computing an output, and the output is computed based only on the last hidden state. Do you think there's an easy way to use a "scalar" criterion such as nn.MSECriterion or nn.BCECriterion with rnn?

Thanks again.

**Comment by nicholas-leonard** [comment]
@jfsantos Yup. Just use stack nn.SelectTable(-1) after the final Sequencer. It will output the last element of the sequence (the last hidden state). You can then feed that through MSE/BCE.

**Comment by jfsantos** [comment]
That works, thanks!

If I manage to get my char-rnn-like code ready before @hughperkins does, I'll submit it as an example of using optim instead of dp.

**Comment by nicholas-leonard** [comment]
@jfsantos awesome!. Would love to see that added as an example.

**Comment by shoaibahmed** [comment]
@jfsantos Can you pl provide your implementation as an example to me for learning purposes?
It will be really helpful.

**Comment by nicholas-leonard** [comment]
@hughperkins The examples folder now contains tons of non-dp examples.
