### ISSUE TITLE
Fast Tensor to Sequence Creation

### ISSUE THREAD

**Issue by uncommoncode** [Element-Research/rnn#8]
There are a few datasets available saved as tensors. I've been converting them to sequences something like the following:

```lua
    -- conversion loop
    local pixels = {}
    for k = 1, raster_size do
        pixels[k] = torch.Tensor({raw_data[k]})
    end
    collectgarbage()

...

   sequenced_layer = rnn.Sequencer(...)
   sequenced_layer:forward(pixels)
```

However the conversion loop seems to be relatively slow. If this is a common operation (converting Tensor data to Sequences), perhaps a faster Lua/C helper function would be a useful feature.

**Comment by nicholas-leonard** [comment]
That is a very inefficient implementation. It requires some complexity to make it fast. This is what I use to store sequences (sentences). Takes a sequence of words stored as a tensor of word ids, and a tensor holding the start index of the sentence of its commensurate word id (the one at the same index).

**Comment by uncommoncode** [comment]
The difficulty I seem to be having is with converting a single tensor to a potentially large tables of tensors. If I naively build the tables before training, I often run into LuaJIT's 2GiB limit. On the other hand if I try to build them on the fly in the training loop, I can first pre-allocate space but then there is a bit of a slowdown moving data around. Pre-allocation here is nice because I only need to create a few objects for each sample in the batch outside of the main training loop requiring less garbage collection.

It sounds like you suggest constructing the sequence on the fly in the training loop?

**Comment by nicholas-leonard** [comment]
Yes. However, instead of doing something like ` pixel = torch.Tensor({raw_data[k]})`, you should have all your sequences concatenated as a large 1D tensor. If this tensor is called `data`,  then you can do `pixel = data:narrow(1, sequence_start_idx, sequence_size)`. Which doesn't allocate any memory (which is where your computer is wasting all that time). Of course, you would need to store a `sequence_start_idx` and `sequence_size` for each sequence somewhere.

**Comment by uncommoncode** [comment]
That works much better, thanks!
