### ISSUE TITLE
module 'ffi' not found lua

### ISSUE THREAD

**Issue by helxsz** [Element-Research/rnn#91]
when I was trying to run the example recurrent-visual-attention.lua,  I got a error saying : module 'ffi' not found lua. any ideas ?

**Comment by hughperkins** [comment]
It's used when you use rnn with cutorch or cltorch, as far as I know.  But it's builtin to luajit I think.  One idea: are you running using base `lua` rather than using `luajit`?

(Details on how ffi gets used:
- line ~209 or so of rnn's Module.lua module calls `param:storage():data()`
- `storage.data()` is defined in `FFI.lua` file, in both cutorch and cltorch (depending on which you are using)

)

**Comment by nicholas-leonard** [comment]
Thanks @hughperkins
