### ISSUE TITLE
CrossEntropyCriterion in SequencerCriterion

### ISSUE THREAD

**Issue by kvitajakub** [Element-Research/rnn#93]
Hello,

I am trying to use regular [CrossEntropyCriterion](https://github.com/torch/nn/blob/master/doc/criterion.md#crossentropycriterion) with SequencerCriterion, but it always fails with `SequencerCriterion only decorates stateless criterions`. I assume that CrossEntropy is stateless, or at least I didn't find anything about that.

Is that correct behaviour? If it is, would be possible to mention it in the docs?

**Comment by nicholas-leonard** [comment]
@kvitajakub The CrossEntropyCriterion is not stateless as it points to a LogSoftMax module internally, which is itself not stateless. A warning is included in the docs, although it doesn't go into too much detail : https://github.com/Element-Research/rnn#rnn.SequencerCriterion . 

To circumvent this, use `ModuleCriterion(ClassNLLCriterion, LogSoftMax)` instead of CrossEntropyCriterion. Should give you the same results.
